Deprecate the `phylum` formula
Adding a `deprecate!` statement to the formula for the existing version
(v6.1.1) does nothing for users who already have this version installed
but it does print a warning and allow install when the version is not
already installed.

Adding the `conflicts_with` statement helps to prevent conflicts with
the `phylum-cli` formula in the core Homebrew tap and shows this error:

```
Error: Cannot install phylum-dev/cli/phylum because conflicting formulae are installed.
  phylum-cli: because both install `phylum` binaries

Please `brew unlink phylum-cli` before continuing.

Unlinking removes a formula's symlinks from /opt/homebrew. You can
link the formula again after the install finishes. You can `--force` this
install, but the build may fail or cause obscure side effects in the
resulting software.
```